### ISSUE TITLE
MissingPluginException(No implementation found for method pickUri on channel uri_picker)

### ISSUE THREAD

**Issue by bradyt** [bradyt/uri_picker#1]
When I go to the `example/` directory and do `flutter run`, the app opens, I press the "Pick URI" button, there is no response in the UI, and I get the following backtrace.

This is contrary to the original code, at https://github.com/bradyt/cone/blob/73a37bfc3b51706c5ac3a113763e1940401e45f3/android/app/src/main/java/info/tangential/cone/MainActivity.java#L46, which has been working.

I've tried to look at documentation, and other examples like file_picker, image_picker, document_picker, etc.

``` text
E/flutter ( 5039): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method pickUri on channel uri_picker)
E/flutter ( 5039): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter ( 5039): <asynchronous suspension>
E/flutter ( 5039): #1      UriPicker.pickUri (package:uri_picker/uri_picker.dart:10:39)
E/flutter ( 5039): <asynchronous suspension>
E/flutter ( 5039): #2      _MyAppState.pickUri (package:uri_picker_example/main.dart:22:29)
E/flutter ( 5039): <asynchronous suspension>
E/flutter ( 5039): #3      _MyAppState.build.<anonymous closure> (package:uri_picker_example/main.dart:52:27)
E/flutter ( 5039): <asynchronous suspension>
E/flutter ( 5039): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter ( 5039): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter ( 5039): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 5039): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter ( 5039): #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter ( 5039): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter ( 5039): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter ( 5039): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter ( 5039): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 5039): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 5039): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 5039): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 5039): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 5039): #17     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 5039): #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 5039): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 5039): #20     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter ( 5039): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter ( 5039): 
```

**Comment by bradyt** [comment]
As pointed out by @crazecoder, this is fixed with for example,

``` diff
@@ -4,7 +4,7 @@ import 'package:flutter/services.dart';
 
 class UriPicker {
   static const MethodChannel _channel =
-      const MethodChannel('uri_picker');
+      const MethodChannel('info.tangential/uri_picker');
 
   static Future<String> pickUri() async {
     final String uri = await _channel.invokeMethod('pickUri');
```
